/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarMenu: typeof import('./src/components/AvatarMenu.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseNavbar: typeof import('./src/components/BaseNavbar.vue')['default']
    BaseSnackbar: typeof import('./src/components/BaseSnackbar.vue')['default']
    BaseSpinner: typeof import('./src/components/BaseSpinner.vue')['default']
    CardLayout: typeof import('./src/components/CardLayout.vue')['default']
    DragDropInput: typeof import('./src/components/DragDropInput.vue')['default']
    FormGenerator: typeof import('./src/components/FormGenerator.vue')['default']
    FullScreenDialog: typeof import('./src/components/FullScreenDialog.vue')['default']
    NavigationMenu: typeof import('./src/components/NavigationMenu.vue')['default']
    NoDataMessage: typeof import('./src/components/NoDataMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SecondaryNavbar: typeof import('./src/components/SecondaryNavbar.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAutocomplete: typeof import('vuetify/components')['VAutocomplete']
    VAvatar: typeof import('vuetify/components')['VAvatar']
    VBtn: typeof import('vuetify/components')['VBtn']
    VBtnToggle: typeof import('vuetify/components')['VBtnToggle']
    VCard: typeof import('vuetify/components')['VCard']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCheckbox: typeof import('vuetify/components')['VCheckbox']
    VCombobox: typeof import('vuetify/components')['VCombobox']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VForm: typeof import('vuetify/components')['VForm']
    VIcon: typeof import('vuetify/components')['VIcon']
    VImg: typeof import('vuetify/components')['VImg']
    VLayout: typeof import('vuetify/components')['VLayout']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VMenu: typeof import('vuetify/components')['VMenu']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VRadio: typeof import('vuetify/components')['VRadio']
    VRadioGroup: typeof import('vuetify/components')['VRadioGroup']
    VRangeSlider: typeof import('vuetify/components')['VRangeSlider']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSlider: typeof import('vuetify/components')['VSlider']
    VSnackbar: typeof import('vuetify/components')['VSnackbar']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VSwitch: typeof import('vuetify/components')['VSwitch']
    VTextarea: typeof import('vuetify/components')['VTextarea']
    VTextField: typeof import('vuetify/components')['VTextField']
    VToolbar: typeof import('vuetify/components')['VToolbar']
    VToolbarTitle: typeof import('vuetify/components')['VToolbarTitle']
    VTooltip: typeof import('vuetify/components')['VTooltip']
  }
}
